sudo: required
services:
  - docker

before_install:
  - docker build -t sgkasif/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sgkasif/react-test npm test   

after_success:
  - docker build -t sgkasif/multi-client ./client
  - docker build -t sgkasif/multi-nginx ./nginx
  - docker build -t sgkasif/multi-server ./server
  - docker build -t sgkasif/multi-worker ./worker
 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
  - docker push sgkasif/multi-client
  - docker push sgkasif/multi-nginx
  - docker push sgkasif/multi-server
  - docker push sgkasif/multi-worker
